### PR TITLE
Update cup-product.tex (Cohomology ring)

### PR DESCRIPTION
**Pull request by Kaiwen-S**
Fix a typo of the cohomology ring of \CP^3. The polynomial ring should be truncated by \alpha^4=0, so the ideal is clear.

### CODE REVIEW

**Comment by Kaiwen-S** [comment]
> Fix a typo of the cohomology ring of \CP^3. The polynomial ring should be truncated by \alpha^4=0, so the ideal is clear.

On pg.667, 

image

This contradicts the theorem on pg. 664

image

Thank you for your time!

**Comment by vEnhance** [comment]
Thanks!

**Comment by Kaiwen-S** [comment]
> Thanks!

By the way, I've sent an email to evan@evanchen.cc on Nov.1st to include a sketch about proving the cohomology ring structure of CP^3 (I'm learning from your book), but I'm unable to change it into a formal argument, so I'm thinking if I can hear some suggestions from you. @vEnhance  

I think that email is likely to be ignored or classified as junk mail.

Thank you.

**Comment by vEnhance** [comment]
I did get the email. I just haven't had a chance to sit down and work through the calculation you sent yet. 

Though I've been away from math for a while now, so to be honest, I'm pretty rusty and not totally sure I'm qualified to evaluate the sketch you sent, but we'll see when I have time.

**Comment by Kaiwen-S** [comment]
Danke schön! (Thank you very much)

> I did get the email. I just haven't had a chance to sit down and work through the calculation you sent yet.
> 
> Though I've been away from math for a while now, so to be honest, I'm pretty rusty and not totally sure I'm qualified to evaluate the sketch you sent, but we'll see when I have time.

**Pull request merged**
