### PR TITLE
Fix typo in algebraic NT chapter

### LINKED ISSUE #230: Typo in example 54.1.6 (page 522, Algebric NT I)
The example claims alpha is a member of Q[sqrt(3)]. If I understand the example correctly, it's probably supposed to be a member of Q[cube root(2)]. The field written right now does not agree with the claim that K has degree 3.

### PR DESCRIPTION
**Pull request by user202729**
Closes #230.

### CODE REVIEW

**Comment by vEnhance** [comment]
Huh looks like we pushed fixes at almost the same time.

**Comment by vEnhance** [comment]
Thanks anyway though.

**Comment by user202729** [comment]
Though I realize there's another set of typo next to the ones fixed by https://github.com/vEnhance/napkin/commit/baab373c662610bfc4c7408dfdb2a64051089a04. (I must have been sleepy while writing this...)

```diff
diff --git a/tex/alg-NT/finite-field.tex b/tex/alg-NT/finite-field.tex
index 56292ca..0264b7b 100644
--- a/tex/alg-NT/finite-field.tex
+++ b/tex/alg-NT/finite-field.tex
@@ -269,19 +269,19 @@ The group $F^\times$ is cyclic of order $16$, so there is some element $g \in>
 that all of the elements in $F$ are
 \[ 0, g^0 = 1, g^1, g^2, \dots, g^{15}.  \]
 Using this knowledge, if we square the nonzero elements, we can easily see that the result are the
-following (note that $g^16 = g^0 = 1$):
-\[ g^0, g^2, g^4, \dots, g^14, g^0, g^2, \dots, g^14.  \]
+following (note that $g^{16} = g^0 = 1$):
+\[ g^0, g^2, g^4, \dots, g^{14}, g^0, g^2, \dots, g^{14}.  \]
 As such, exactly half of the elements --- 8 elements --- in $F^\times$ are quadratic residues!
 
 Checking whether there is an element $x$ such that $x^2 = -1$ isn't much harder.
-First, where may $-1$ appear in the sequence $\{g^0, g^1, \dots, g^15 \}$?
+First, where may $-1$ appear in the sequence $\{g^0, g^1, \dots, g^{15} \}$?
 If you find an explicit value of $g$ (you can pick $g = 3$ for instance), you will see that $g^8 =
 -1$. But, even without an explicit calculation, you can still see that, because:
 \begin{ques}
     Note that the equation $x^2 = 1$ has only $2$ roots, $1$ and $-1$.
     Using group operations in the group $F^\times$, what does the equation say?
 \end{ques}
-We have $g^8 = -1$, so $(g^4)^2 = (g^12)^2 = -1$, so we're done.
+We have $g^8 = -1$, so $(g^4)^2 = (g^{12})^2 = -1$, so we're done.
 \end{example}
 
 So, why is the proposition true? Consider a finite field $F$ of order a prime power $q$.
```

**Comment by vEnhance** [comment]
Haha, missing curly braces is no big deal. I just fixed those too.

**Pull request closed without merging**
